Foodie/Foodie/Controllers/CommentController.cs
using Foodie.Helpers;
using Foodie.Models;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Foodie.Controllers
{

    public class CommentController : Controller
    {
        private string connectionString = ConfigurationManager.ConnectionStrings["FoodieDatabase"].ConnectionString;
        // GET: Comment
        public ActionResult Create(string reviewId)
        {
            var newComment = new CommentViewModel();
            newComment.ReviewId = reviewId; // 
            newComment.UserId = (string)Session["pId"];
            newComment.UserName = (string)Session["userName"];

            return View(newComment);
        }

        [HttpPost]
        public ActionResult Create(CommentViewModel comment)
        {
            //create comment
            Querries.insertComment(comment);
            return RedirectToAction("Details", "Review", new { ReviewId = comment.ReviewId});
        }

        public ActionResult Details(string commentId)
        {

            //CommentViewModel comment = Querries.getComment(commentId);
            //return View(comment);
            return View();
        }

    }
}

Foodie/Foodie/Controllers/ReviewController.cs
using Foodie.Helpers;
using Foodie.Models;
using Npgsql;
using NpgsqlTypes;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Foodie.Controllers
{
    public class ReviewController : Controller
    {
        private string connectionString = ConfigurationManager.ConnectionStrings["FoodieDatabase"].ConnectionString;
        // GET: Review
        public ActionResult Index(List<Foodie.Models.Review> modelList)
        {
            return View(modelList);
        }

        //GET: create Review
        public ActionResult Create(string restaurantId)
        {
            Restaurant restaurant = Querries.getRestaurant(restaurantId);
            ViewBag.restaurantId = restaurantId;
            CreateReviewModel cModel = new CreateReviewModel();
            cModel.RestaurantId = restaurantId;
            cModel.RestaurantName = restaurant.Name;
            return View(cModel);
        }
        //POST: create Review
        [HttpPost]
        public ActionResult Create(Foodie.Models.CreateReviewModel model)
        {
            Review review = CreateReview(model);
            return RedirectToAction("Details", "Review", new {reviewId = review.ReviewId.ToString()});
        }

        //GET: review details page
        public ActionResult Details(string reviewId)
        {
            //later we can consolidate this into 1 stored procedure instead of 2
            Review review = Querries.getReview(reviewId);
            review.comments = Querries.getReviewComments(reviewId);
            return View(review);
        }

        [HttpPost]
        public JsonResult rateHelpfulness(string reviewId, int rating, string authorId)
        {
            HelpfullnessViewModel helpModel = new HelpfullnessViewModel();
            Guid personId = (Guid)Session["pId"];
            helpModel.HelpfulId = Guid.NewGuid().ToString();
            helpModel.RatingUserId = personId.ToString();
            helpModel.ReviewId = reviewId;
            helpModel.Rating = rating;
            helpModel.AuthorId = authorId;
            double newAverage = Querries.rateReviewHelpfullness(helpModel);
            return Json(newAverage, JsonRequestBehavior.AllowGet);
        }
            
        //}

        /// <summary>
        /// Create a Review
        /// </summary>
        /// <param name="?"></param>
        /// <returns> the created Review model</returns>
        private Review CreateReview(CreateReviewModel crModel)
        {
            using (NpgsqlConnection conn = new NpgsqlConnection(connectionString))
            {
                using (NpgsqlCommand command = conn.CreateCommand())
                {
                    conn.Open();
                    Review review = new Review();
                    int reviewId = 0;
                    //command.CommandText = string.Format(CultureInfo.InvariantCulture, "select max(UserId) from \"{0}\"", "Reviews");
                    //command.Prepare();
                    //reviewId = Convert.ToInt32(command.ExecuteScalar());
                    //incrementing pid
                    //reviewId = reviewId + 1;



                    //grab the user who's currently logged in
                    Guid personId = (Guid)Session["pId"];
                    string userName = (string)Session["Username"];
                    review.ReviewId = Guid.NewGuid();
                    review.UserId = personId;
                    review.UserName = userName;
                    review.ReviewText = crModel.ReviewText;
                    review.RestaurantName = crModel.RestaurantName;
                    review.RestaurantId = new Guid(crModel.RestaurantId);
                    review.DatePosted = DateTime.Now;
                    review.Rating = crModel.Rating;
                    using (NpgsqlCommand comm = conn.CreateCommand())
                    {
                        comm.CommandText = string.Format(CultureInfo.InvariantCulture,
                            "INSERT INTO \"Reviews\" (\"ReviewId\", \"ReviewText\", \"AverageReviewRating\", \"DatePosted\", \"UserId\", \"RestaurantId\", \"Rating\") Values (@ReviewId, @ReviewText, @AverageReviewRating, @DatePosted, @UserId, @RestaurantId, @Rating)");
                        comm.Parameters.Add("@ReviewId", NpgsqlDbType.Char, 36).Value = review.ReviewId;
                        comm.Parameters.Add("@ReviewText", NpgsqlDbType.Text).Value = review.ReviewText;
                        comm.Parameters.Add("@AverageReviewRating", NpgsqlDbType.Real).Value = 0.0;
                        comm.Parameters.Add("@DatePosted", NpgsqlDbType.Date).Value = review.DatePosted;
                        comm.Parameters.Add("@UserId", NpgsqlDbType.Char, 36).Value = review.UserId;
                        comm.Parameters.Add("@RestaurantId", NpgsqlDbType.Char, 36).Value = review.RestaurantId;
                        comm.Parameters.Add("@Rating", NpgsqlDbType.Integer).Value = review.Rating;
                        try
                        {
                            comm.Prepare();
                            if (comm.ExecuteNonQuery() > 0)
                            {
                                //Console.WriteLine("Success");
                            }
                            else
                            {
                                //Console.WriteLine("Failure");
                            }

                        }
                        catch (NpgsqlException e)
                        {
                            Trace.WriteLine(e.ToString());
                        }
                        finally
                        {
                            if (conn != null)
                            {
                                conn.Close();
                            }
                        }

                    }

                    return review;
                }
            }
        }
    }
}

Foodie/Foodie/Views/Review/Create.cshtml
@model Foodie.Models.CreateReviewModel
@{
    ViewBag.Title = "Create";
}

<h2>Submit Review</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    
    <fieldset>
        <legend> Review Submission Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.RestaurantName)
                @Html.DisplayFor(m  => m.RestaurantName)
            </li>
            <li>
                @Html.LabelFor(m => m.Rating)
                @Html.TextBoxFor( m => m.Rating)
                
            </li>
            <li>
                @Html.LabelFor(m => m.ReviewText)
                @Html.TextAreaFor(m => m.ReviewText)
            </li>
        </ol>
        <input type="submit" value="Submit Review" />
    </fieldset>
}

Foodie/Foodie/Views/Review/Details.cshtml
@model Foodie.Models.Review
@{
    ViewBag.Title = "View";
}
<h2>Review for @Model.RestaurantName</h2>
    <fieldset>
        <ol>
            <li>
                @Html.LabelFor(m => m.UserName)
                @Html.DisplayTextFor(m => m.UserName)
            </li>
            <li>
                @Html.LabelFor(m => m.DatePosted)
                @Html.DisplayFor(m => m.DatePosted)
            </li>
            <li>
                @Html.LabelFor(m => m.Rating)
                @Html.DisplayFor(m => m.Rating)
            </li>
            <li>
                @Html.LabelFor(m => m.ReviewText)
                @Html.DisplayTextFor(m => m.ReviewText)
            </li>
        </ol>
    </fieldset>
@{
    var com = new Foodie.Models.CommentViewModel();
    com.ReviewId = Model.ReviewId.ToString();
    com.UserName = (string)Session["Username"];
    com.UserId = ((Guid)Session["pId"]).ToString();
    Html.RenderPartial("_AddComment", com);
}
@foreach (Foodie.Models.CommentViewModel comment in Model.comments)
{
    Html.RenderPartial("_CommentDetails", comment);
}
@section Scripts{
    @Scripts.Render("~/Scripts/partialReviewScript.js");
}

Foodie/Foodie/Views/Review/Index.cshtml
@model List<Foodie.Models.Review>
@{
    ViewBag.Title = "Reviews";
}

<h2>Index</h2>
    @for (int i = 0; i < Model.Count; i++)
    {
  
            <ul>
                    <li>
                        @Html.LabelFor(m => m[i].UserName)
                        @Html.DisplayTextFor(m => m[i].UserName)
                    </li>
                    <li>
                        @Html.LabelFor(m => m[i].DatePosted)
                        @Html.DisplayFor(m => m[i].DatePosted)
                    </li>
                    <li>
                        @Html.LabelFor(m => m[i].RestaurantName)
                        @Html.DisplayFor(m => m[i].RestaurantName)
                    </li>
                    <li>
                        @Html.LabelFor(m => m[i].ReviewText)
                        @Html.DisplayFor(m => m[i].ReviewText)
                    </li>   
           </ul>      
  
    }

Foodie/Foodie/Views/Review/_AddComment.cshtml
@model Foodie.Models.CommentViewModel

@using (Html.BeginForm("Create", "Comment", FormMethod.Post, null)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Comments</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.ReviewId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            <label for="UserName">UserName</label>
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @Html.HiddenFor(m => m.ReviewId)
        @Html.HiddenFor(m => m.UserId)
        <div class="form-group">
            <label for="CommentText">@Model.UserName</label>
            @*@Html.LabelFor(model => model.CommentText, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.CommentText, new { htmlAttributes = new { @class = "form-control" } })
                <input type="submit" value="Comment" class="btn btn-default" />
                @Html.ValidationMessageFor(model => model.CommentText, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.commentOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.commentOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.commentOrder, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>*@
    </div>
}

Foodie/Foodie/Views/Review/_CommentDetails.cshtml
@model Foodie.Models.CommentViewModel

<div>
            <b>
                @Html.DisplayFor(model => model.UserName)
            </b>
            @Html.DisplayFor(model => model.CommentText)
</div>